In [4]:
import pandas as pd

temp_data = pd.read_csv ('test.csv').iloc[:99]
temp_data

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,19556,Female,Loyal Customer,52,Business travel,Eco,160,5,4,...,5,5,5,5,2,5,5,50,44.0,satisfied
1,1,90035,Female,Loyal Customer,36,Business travel,Business,2863,1,1,...,4,4,4,4,3,4,5,0,0.0,satisfied
2,2,12360,Male,disloyal Customer,20,Business travel,Eco,192,2,0,...,2,4,1,3,2,2,2,0,0.0,neutral or dissatisfied
3,3,77959,Male,Loyal Customer,44,Business travel,Business,3377,0,0,...,1,1,1,1,3,1,4,0,6.0,satisfied
4,4,36875,Female,Loyal Customer,49,Business travel,Eco,1182,2,3,...,2,2,2,2,4,2,4,0,20.0,satisfied
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,94,119896,Female,Loyal Customer,46,Business travel,Business,912,1,1,...,4,4,4,4,5,4,4,5,0.0,satisfied
95,95,88853,Female,Loyal Customer,52,Personal Travel,Eco Plus,406,3,4,...,2,2,3,2,3,2,4,0,0.0,neutral or dissatisfied
96,96,24895,Female,Loyal Customer,38,Personal Travel,Eco,397,2,5,...,5,5,4,4,5,5,5,0,0.0,neutral or dissatisfied
97,97,31122,Male,Loyal Customer,35,Business travel,Business,2409,3,3,...,4,4,4,4,3,4,3,0,0.0,satisfied
98,98,91231,Female,Loyal Customer,41,Personal Travel,Eco,545,2,2,...,4,1,3,4,1,4,4,0,0.0,neutral or dissatisfied

In [5]:
temp_data.columns

Index(['Unnamed: 0', 'id', 'Gender', 'Customer Type', 'Age', 'Type of Travel',
       'Class', 'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes',
       'satisfaction'],
      dtype='object')